In [ ]:
import numpy as np

vector = np.array([1,2,3,4])
vector *= 2
print(vector)  # Output: [2 4 6 8]
reshaped_vector = vector.reshape(2, 2)
print(reshaped_vector)

raveled_vector = reshaped_vector.ravel()
print(raveled_vector)  # Output: [2 4 6 8]

[2 4 6 8]


In [6]:
arr = np.array([1, 2, 3 , 4, 5, 6 , 7 , 8])
print("basic slicing",arr[2:5])  # Output: [3 4 5]
print("advanced slicing",arr[[1, 3, 5]])  # Output: [2 4 6]
print("withstep",arr[1:7:3])  # Output: [2 4 6]

arr_2d = np.array([[1, 2, 3],
                   [3, 4, 5],
                   [4, 3, 2]])
print("specific element", arr_2d[1, 2])
print("entire row", arr_2d[2, :])

basic slicing [3 4 5]
advanced slicing [2 4 6]
withstep [2 5]
specific element 5
entire row [4 3 2]


In [9]:
unshorted_array = np.array([3, 1, 4, 2])
print("sorted array", np.sort(unshorted_array))

arr1 = np.array([[1, 2, 3],
                [3, 8, 5],
                [2, 1, 1]])
print("sorted 2d arr by columns", np.sort(arr1, axis=0))
print("sorted 2d arr by rows", np.sort(arr1, axis=1))

sorted array [1 2 3 4]
sorted 2d arr by columns [[1 1 1]
 [2 2 3]
 [3 8 5]]
sorted 2d arr by rows [[1 2 3]
 [3 5 8]
 [1 1 2]]


In [11]:
num_array = np.array([1 , 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = (num_array % 2 == 0)
even_numbers = num_array[mask]
print("even numbers", even_numbers)  # Output: [ 2  4  6  8 10] 

indices = np.where(num_array > 5)
print("indices of elements greater than 5", indices) 

random = np.random.randint(1, 90, 9)
print("random array", random)
condition = np.where(random > 30, 'big', 'small')   
print("condition applied", condition)


even numbers [ 2  4  6  8 10]
indices of elements greater than 5 (array([5, 6, 7, 8, 9]),)
random array [73 11  1 56 29 31 81 12 49]
condition applied ['big' 'small' 'small' 'big' 'small' 'big' 'big' 'small' 'big']


In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
sum_array = np.concatenate((arr1, arr2))
print("concatenated array", sum_array)  # Output: [1 2 3 4 5 6]

concatenated array [1 2 3 4 5 6]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([[19, 22], [43, 50]])
dot = np.dot(a, b)
print("compatibility shapes", a.shape == b.shape)
print("matrix multiplication result", c)  # Output: [[19 22] [43 50]]
